### ISSUE TITLE
Issue first run

### ISSUE THREAD

**Issue by Emibergo02** [Mathieu2301/Temp-Mail-API#2]
Error: Can't parse server response
    at IncomingMessage.<anonymous> (/root/node_modules/temp-mail-api/request.js:22:22)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
i copypasted your test code

**Comment by Mathieu2301** [comment]
Fixed in [1.1.1](https://github.com/Mathieu2301/Temp-Mail-API/commit/1838d90b954595b4477c826600aef0d06f6f6995) !

**Comment by Mathieu2301** [comment]
Thanks for reporting

**Comment by Steccah** [comment]
I'm having the same issue on the 1.1.1 version
```
Error: Can't parse server response
    at IncomingMessage.<anonymous> (E:\Users\McStecca\Desktop\code\nodejs\sugarbot\node_modules\temp-mail-api\request.js:22:22)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by Mathieu2301** [comment]
Yes, temp-mail.org has blocked the API and changed the way it works :/

**Comment by 1aerostorm** [comment]
@Mathieu2301 sh*t happens... But why not update this npm module? Or at least deprecate it.
